# Generated by Django 5.2.7 on 2025-11-10 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='business.category'),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('rejected', 'Rejected')], default='published', max_length=15),
        ),
        migrations.AlterField(
            model_name='business',
            name='subcategories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'level__gt': 0}, related_name='subcategorized_businesses', to='business.category'),
        ),
        migrations.AlterField(
            model_name='business',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
